# Generated by Django 5.2.17 on 2026-09-11 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='organization',
            field=models.CharField(default='', max_length=255),
        ),
    ]
